apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: backend
  template:
    metadata:
      labels:
        app: backend
    spec:
      initContainers:
      - name: wait-for-model
        image: mlflow:custom
        imagePullPolicy: IfNotPresent
        command: 
          - "sh"
          - "-c"
          - |
            echo "Waiting for MLflow Service..."
            until curl -s -f http://mlflow-service:5000/health; do sleep 2; done
            echo "Checking for 'LoanPredictionModel'..."
            until curl -s -f "http://mlflow-service:5000/api/2.0/mlflow/registered-models/get?name=LoanPredictionModel"; do 
              echo "Model not found. Waiting..."
              sleep 5
            done
            echo "Model found!"

      containers:
      - name: backend
        image: backend:custom
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 2000
        env:
        - name: MLFLOW_TRACKING_URI
          value: "http://mlflow-service:5000"
        - name: PYTHONUNBUFFERED
          value: "1"
        command: ["gunicorn", "app:app", "-b", "0.0.0.0:2000", "--workers", "2", "--timeout", "120"]
        
        # --- CRITICAL FIX START ---
        volumeMounts:
        - name: mlflow-storage
          mountPath: /artifacts
        # --- CRITICAL FIX END ---

      # --- CRITICAL FIX START ---
      volumes:
      - name: mlflow-storage
        persistentVolumeClaim:
          claimName: mlflow-artifacts-pvc
      # --- CRITICAL FIX END ---

---
apiVersion: v1
kind: Service
metadata:
  name: backend-service
spec:
  selector:
    app: backend
  ports:
    - protocol: TCP
      port: 2000
      targetPort: 2000