apiVersion: apps/v1 # API-group/Version-Schema
kind: Deployment
metadata:
  name: mlflow # Deployment identity (API object) -> (Mandatory)
spec:
  replicas: 1 # Desired state (how many Pods) -> (enforced via ReplicaSet)
  selector:
    matchLabels:
      app: mlflow # Ownership rule (which Pods I manage) -> This Deployment manages all Pods that have app=mlflow
  template:
    metadata:
      labels:
        app: mlflow # Pod identity (how Pods are labeled)
    # selector.matchLabels must be a subset of template.metadata.labels
    spec:
      containers:
      - name: mlflow
        image: mlflow:custom  # <--- YOUR CUSTOM IMAGE 
        # (tag from docker build -t mlflow:custom -f backend/mlflow/Dockerfile ./backend/mlflow)
        # Using a local custom image in Kubernetes (specifically kind) the Cluster can't see your laptop's Docker images.
        # For this reason, these images build on premises and then load them on the Kind cluster node.
        # If you want to avoid this, pull the default image from Dockerhub instead.
        imagePullPolicy: IfNotPresent # <--- CRITICAL: Don't try to pull from Docker Hub
        ports:
        - containerPort: 5000
        command: ["mlflow", "server"]
        args: [
          "--host", "0.0.0.0",
          "--port", "5000",
          "--backend-store-uri", "sqlite:////data/mlflow.db",
          "--default-artifact-root", "/artifacts"
        ]
        # NOW WE USE THE CURL YOU INSTALLED
        # Probes belong to containers, not controllers.
        livenessProbe: # "Is this container dead/frozen?" Then K8s KILLS the container and starts a new one.
          exec:
            command:
            - curl
            - -f
            - http://localhost:5000/health
          initialDelaySeconds: 10
          periodSeconds: 30
        # "Are you ready to accept traffic?" K8s hides the container from the Service (LoadBalancer). 
        # No traffic gets sent there, but the container keeps running.
        # “Be very patient with readiness, strict with liveness”
        readinessProbe: 
          exec:
            command:
            - curl
            - -f
            - http://localhost:5000/health
          initialDelaySeconds: 5
          periodSeconds: 10
        # Container perspective
        volumeMounts:
        - name: db-volume
          mountPath: /data
        - name: artifacts-volume
          mountPath: /artifacts # Job writes to /artifacts -> MLflow is configured to treat /artifacts as artifact root
          # Consistency is logical, not cosmetic.
      # Pod perspective
      volumes:
      - name: db-volume
        persistentVolumeClaim:
          claimName: mlflow-db-pvc
      - name: artifacts-volume
        persistentVolumeClaim:
          claimName: mlflow-artifacts-pvc
---
apiVersion: v1
kind: Service
metadata:
  name: mlflow-service
spec:
  selector:
    app: mlflow
  ports:
  - protocol: TCP
    port: 5000
    targetPort: 5000